@Kanban_HostAddress = https://localhost:7262

GET {{Kanban_HostAddress}}/story/
Accept: application/json

###

POST {{Kanban_HostAddress}}/story
Content-Type: application/json

{
  "id": 1,
  "name": "TestStory",
  "ownerId": 1,
  "boardId": 1
}

###

GET {{Kanban_HostAddress}}/user
Accept: application/json

###

POST {{Kanban_HostAddress}}/user
Content-Type: application/json

{
  "id": 1002,
  "name": "Test1000"
}

###

PUT {{Kanban_HostAddress}}/user
Content-Type: application/json

{
  "id": 1102,
  "name": "Test1000"
}

###

GET {{Kanban_HostAddress}}/board
Accept: application/json

###

POST {{Kanban_HostAddress}}/board
Content-Type: application/json

{
  "id": 1,
  "name": "NewBoard",
  "ownerId": "1"
}

###

GET {{Kanban_HostAddress}}/status
Accept: application/json

###

POST {{Kanban_HostAddress}}/status
Content-Type: application/json

{
  "id": 1,
  "name": "NewStatus"
}

###
