@Kanban_HostAddress = https://localhost:7262

GET {{Kanban_HostAddress}}/story/
Accept: application/json

###

POST {{Kanban_HostAddress}}/story
Content-Type: application/json

{
  "id": 1,
  "name": "TestItAgain",
  "ownerId": 1,
  "boardId": 1
}

###

PUT {{Kanban_HostAddress}}/story
Content-Type: application/json

{
  "id": 1019,
  "name": "Buy Groceries Now Test2000+",
  "description": "1 L milk\n\r1 Juicy Lemon",
  "statusId": 1,
  "ownerId": 1,
  "boardId": 1
}

###

PATCH {{Kanban_HostAddress}}/story
Content-Type: application/json

{
  "id": 1019,
  "name": "Buy Groceries Now Test2000+",
  "description": "1 L milk\n\r1 Juicy Lemon",
  "statusId": 1,
  "ownerId": 1,
  "boardId": 1
}

###

GET {{Kanban_HostAddress}}/user
Accept: application/json

###

POST {{Kanban_HostAddress}}/user
Content-Type: application/json

{
  "id": 1002,
  "name": "Test1000"
}

###

PUT {{Kanban_HostAddress}}/user
Content-Type: application/json

{
  "id": 1102,
  "name": "Test1000"
}

###

GET {{Kanban_HostAddress}}/board
Accept: application/json

###

POST {{Kanban_HostAddress}}/board
Content-Type: application/json

{
  "id": 1,
  "name": "NewBoard",
  "ownerId": "1",
  "created": "2050-01-22T11:24:51.5633333"
}

###

PATCH {{Kanban_HostAddress}}/board/1
Content-Type: application/json-patch+json

[
  {
    "op": "replace", "path": "/lastUpdated", "value": "2040-01-22T11:24:51.5633333"
  }
]

###

GET {{Kanban_HostAddress}}/status
Accept: application/json

###

POST {{Kanban_HostAddress}}/status
Content-Type: application/json

{
  "id": 1,
  "name": "NewStatus"
}

###

PUT {{Kanban_HostAddress}}/status
Content-Type: application/json

{
  "id": 1,
  "name": "NewStatus"
}

###
